# Generated by Django 5.2 on 2025-04-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_alter_category_slug_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="../front/public/productcard"
            ),
        ),
    ]
