# Generated by Django 5.2 on 2025-04-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_alter_category_slug_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
